kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: keycloak-rollout-run-
spec:
  serviceAccountName: chains-runner
  pipelineRef:
    name: keycloak-pipeline
  podTemplate:
     securityContext:
        runAsNonRoot: false
  workspaces:
    - name: buildworkspace
      persistentVolumeClaim:
        claimName: pipeline-workspace

